[Feature] Lines without actor
ioprojekt-2019/ScenarioQualityChecker pull request #13
Opened 2019-11-03 11:33 UTC by ChairChandler

2019-11-03 11:42 UTC, ChairChandler commented
https://trello.com/c/19wMoZg1/4-element-4-wykrywanie-linijek-bez-aktora

2019-11-03 16:22 UTC, Unh3ck3d requested changes

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/service/ScenarioLinesWithoutActorInFirstWordService.java
> +public interface ScenarioLinesWithoutActorInFirstWordService {
FindScenarioStepNamesNotStartingWithActorService would be a better name, it's important to name classes and methods using names related to domain of the problem.

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/service/ScenarioLinesWithoutActorInFirstWordService.java
> +    public ArrayList<String> getLines(ScenarioDTO scenarioDTO);
Like above

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioLinesWithoutActorInFirstWordServiceImpl.java
> +
In your methods sometimes there is a new line at the beginning of the method body and sometimes not. Try to stay consistent. It would be better to choose the version without the new line, cause the new line in that case doesn't make code any more readable.

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioLinesWithoutActorInFirstWordServiceImpl.java
> +public class ScenarioLinesWithoutActorInFirstWordServiceImpl implements ScenarioLinesWithoutActorInFirstWordService {
From what I gathered from the task description in xls file keywords in step names should be ignored. I don't see that implemented.

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioLinesWithoutActorInFirstWordServiceImpl.java
> +    private ArrayList<String> getIncorrectNestedStepsNames(ArrayList<ScenarioStepDTO> nestedSteps) {
What does it mean incorrect? When someone reads a method name it should be self explanatory.

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioLinesWithoutActorInFirstWordServiceImpl.java
> +    private boolean isLineCorrect(String line) {
Method body can be replaced with something like that:
return actors.stream().anyMatch(actor -> Pattern.compile("^" + actor + "\\b").matcher(line).find());

2019-11-03 16:22 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/rest/ScenarioLinesWithoutActorInFirstWordController.java
> +     * Method: GET<br>
You wrote Method: GET but few lines below there is a PostMapping annotation. It should be GetMapping.

2019-11-03 16:22 UTC, ZaluskiDominik commented on src/main/java/pl/put/poznan/transformer/rest/ScenarioLinesWithoutActorInFirstWordController.java
> +     *              "0" :"SOMETHING ACTOR",
It's not a valid JSON. Arrays can't have keys, only values. Furthermore if you give examples then it should be meaningful for the reader, make it look more like an actual step instruction(like in xls file example).

2019-11-03 16:22 UTC, ZaluskiDominik commented on src/main/java/pl/put/poznan/transformer/rest/ScenarioLinesWithoutActorInFirstWordController.java
> +    @PostMapping("/scenario/lines/incorrect")
Wrong http method and name of an endpoint. @ClouddJR @CiesielskiB How to name it? Something like /scenario/steps/not-starting-with-actor? Or maybe /scenario/steps?fiter= and here goes the filter name. That last one would probably need to return all steps when filter is not given.

2019-11-03 16:22 UTC, ZaluskiDominik commented on src/main/java/pl/put/poznan/transformer/rest/ScenarioLinesWithoutActorInFirstWordController.java
> +    public ResponseEntity<Map<String, Map<String, String>>> getScenarioLinesWithoutActorInFirstWordAction(@RequestBody ScenarioDTO scenarioDTO) {
Better create separate DTO for reponse, e.g. FlattenedStepsDTO it will be cleaner.

2019-11-13 15:54 UTC, CiesielskiB commented on src/main/java/pl/put/poznan/transformer/logic/service/ScenarioLinesWithoutActorInFirstWordService.java
> +public interface ScenarioLinesWithoutActorInFirstWordService {
chekced looks fine

2019-11-13 15:54 UTC, CiesielskiB commented on src/main/java/pl/put/poznan/transformer/logic/service/ScenarioLinesWithoutActorInFirstWordService.java
> +    public ArrayList<String> getLines(ScenarioDTO scenarioDTO);
Checked looks fine

2019-11-13 15:55 UTC, CiesielskiB commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioLinesWithoutActorInFirstWordServiceImpl.java
> +
I don't see any enters anymore, even if there is any I would let it go :)

2019-11-13 15:57 UTC, CiesielskiB commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioLinesWithoutActorInFirstWordServiceImpl.java
> +public class ScenarioLinesWithoutActorInFirstWordServiceImpl implements ScenarioLinesWithoutActorInFirstWordService {
Keyword have been removed from step names before checking so I think its correct now

2019-11-13 16:24 UTC, CiesielskiB requested changes

2019-11-13 16:24 UTC, CiesielskiB commented on src/test/java/pl/put/poznan/transformer/logic/serviceimpl/FindScenarioStepNamesNotStartingWithActorServiceImplTest.java
> +        };
This method creates ArrayList substNames, never assigns anything to it and returns it, you are using cSteps in here already instead I think anyway. But my concern is that you use some simmilar alorythm in your tests to test your initial service? Does it make sense to test service's method result with another result of another nearly identical method ?
Also it dosen't check if keyword is at the beggining or not as far as I'm concerned

2019-11-13 16:24 UTC, CiesielskiB commented on src/test/java/pl/put/poznan/transformer/rest/FindScenarioStepNamesNotStartingWithActorServiceControllerTest.java
> +    private FindScenarioStepNamesNotStartingWithActorService findScenarioStepNamesNotStartingWithActorService;
please make this name shorter, just the variable, call it 'service' if the class name is that long

2019-11-13 19:13 UTC, CiesielskiB approved these changes

2019-11-13 19:18 UTC, merged