[Feature] Count keywords in steps
ioprojekt-2019/ScenarioQualityChecker pull request #9
Opened 2019-11-01 17:44 UTC by ClouddJR

2019-11-01 17:48 UTC, ClouddJR commented
![](https://github.trello.services/images/mini-trello-icon.png) [Element 3 - zliczanie słów kluczowych](https://trello.com/c/q5OdUrpR/3-element-3-zliczanie-s%C5%82%C3%B3w-kluczowych)

2019-11-01 22:06 UTC, Unh3ck3d requested changes

2019-11-01 22:06 UTC, Unh3ck3d commented on src/main/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioKeywordsCounterServiceImpl.java
> +    private final String[] keywords = {"IF", "ELSE", "FOR EACH"};
I think it would be good to put those keywords in one global place, so that they can be accessed by other classes and eventually changed later on. For example in application.properties config file, those values could be then injected to your keywords array with @value annotation.

2019-11-01 22:06 UTC, Unh3ck3d commented on src/test/java/pl/put/poznan/transformer/logic/serviceimpl/ScenarioKeywordsCounterServiceImplTest.java
> +public class ScenarioKeywordsCounterServiceImplTest {
There should be a test for case when among other steps a step is given that doesn't contain keyword, or it contains keyword but its not at the beginning of the step's name

2019-11-01 22:06 UTC, ZaluskiDominik commented on src/test/java/pl/put/poznan/transformer/rest/ScenarioKeywordsCounterControllerTest.java
> +    private void assertHaveStepsCountAnd200HttpStatus(ResponseEntity<Map<String, Integer>> response) {
Name keywoardsCount instead of stepsCount

2019-11-02 13:43 UTC, Unh3ck3d approved these changes
Approved & Ready to merge

2019-11-02 13:45 UTC, merged